user registration test added. Page factory implemented
oryabinskiy/AQA_Training pull request #1
Opened 2017-06-08 13:53 UTC by oryabinskiy

Can't create new user, an error appears

2017-06-08 13:59 UTC, denysLystopadskyy commented on src/main/java/pages/AdminPage.java
> +import org.openqa.selenium.support.FindBy;
Test

2017-06-08 21:07 UTC, denysLystopadskyy requested changes

2017-06-08 21:07 UTC, denysLystopadskyy commented on src/main/java/pages/AdminPage.java
> +    @FindBy(xpath = ".//*[@id='header']/div[2]/div[5]/div[1]")
Updated Locator

2017-06-08 21:07 UTC, denysLystopadskyy commented on src/main/java/pages/AdminPage.java
> +    @FindBy(xpath = ".//*[@id='header']/div[2]/div[5]/div[2]/div/ul/li[3]/div/a")
Update Locator

2017-06-08 21:07 UTC, denysLystopadskyy commented on src/main/java/pages/AdminPage.java
> +    @FindBy(css = "[id*=login]")
Is it necessary to use * in this and following cases?

2017-06-08 21:07 UTC, denysLystopadskyy commented on src/main/java/pages/AdminPage.java
> +    @FindBy(xpath = ".//*[@id='header']/div[2]/div[5]/div[2]/div/ul/li[3]/div/a")
If you do not use text in locator, please use css

2017-06-08 21:07 UTC, denysLystopadskyy commented on src/main/java/pages/AdminPage.java
> +    public void clickOnElement(WebElement webElement) {
It is nice to have a wrapper if you wish to update logic. In future you can do it in one place. 
As it is a general purpose method you should move it to base class or to util class

2017-06-08 21:07 UTC, denysLystopadskyy commented on src/main/java/pages/AdminPage.java
> +    @FindBy(xpath = ".//*[@id='header']/div[2]/div[5]/div[2]/div/ul/li[3]/div/a")
Please, look through all locators and update them

2017-06-08 21:07 UTC, denysLystopadskyy commented on src/main/java/pages/AdminPage.java
> +    @FindBy(css = "[class*=ui-dialog-titlebar-close]")
If you use only class for locator you can use className

2017-06-08 21:07 UTC, denysLystopadskyy commented on src/main/java/pages/AdminPage.java
> +    public String getCurrentDate(){
This will look good in some utils class

2017-06-08 21:07 UTC, denysLystopadskyy commented on src/main/java/pages/BasePage.java
> +        return wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath(locator)));
Minor: you can do it on line.
Does not matter in general)

2017-06-08 21:07 UTC, denysLystopadskyy commented on src/main/java/pages/HomePage.java
> +    @FindBy(css="[id*=login-email]")
If it is id, you should use id, not css locator. Please check all the places.

2017-06-12 08:13 UTC, oryabinskiy commented
Locators updated. Screenshots added

2017-06-12 08:13 UTC, closed without merging